/* Internal QA artifact (never a learner screen): course source → module → drug type → unit → concept →
   objectives, with lesson / question / visual / practice / test coverage. Writes docs/COVERAGE.md.
   Usage: npx tsx --tsconfig tsconfig.json scripts/coverage-matrix.ts */
import { writeFileSync } from "node:fs";
import { CONCEPT_BY_ID, CONCEPTS, TOPICS, WORLD_BY_ID } from "@/data/curriculum";
import { QUESTIONS } from "@/data/bank";
import { STATIC_ACTIVITIES, TEMPLATES } from "@/data/activities";
import { GROUPS, UNIT_BY_ID } from "@/data/library";
import { LESSON_BY_UNIT, LESSONS, teachingFor } from "@/data/lessons";
import { OBJECTIVES, objectivesForConcept } from "@/data/objectives";
import { questionLevel } from "@/lib/engine/learning";
import { EXAM_TYPES } from "@/lib/engine/exam";

const qFor = (c: string) => QUESTIONS.filter((q) => q.concept === c);
const actsFor = (c: string) => STATIC_ACTIVITIES.filter((a) => a.concepts.includes(c)).length + TEMPLATES.filter((t) => t.concepts.includes(c)).length;
const yes = (b: boolean) => (b ? "✓" : "✗");

const lines: string[] = [];
const out = (s = "") => lines.push(s);
out("# Pharm Quest — content coverage matrix (internal QA)");
out();
out("Generated by `scripts/coverage-matrix.ts`. Not shown to the learner. ✓ = covered, ✗ = gap.");
out("Practice ✓ = ≥ 2 recognition items (guided) + ≥ 1 application/clinical item. Test ✓ = ≥ 3 exam-format items (MCQ/SATA/fill/TF).");
out("Calculation concepts use generated problems (unlimited), so their question counts read 0 by design.");
out();
let gaps = 0;
for (const g of GROUPS) {
  out(`## ${WORLD_BY_ID[g.module].module} · ${g.title}`);
  out();
  out("| Source | Drug type / unit | Concept | Objectives | Lesson | Qs (L2/L3/L4/L5/L6) | Visual | Practice | Test |");
  out("|---|---|---|---|---|---|---|---|---|");
  for (const uid of g.units) {
    const u = UNIT_BY_ID[uid];
    for (const cid of u.concepts) {
      const c = CONCEPT_BY_ID[cid];
      const qs = qFor(cid);
      const lv = [2, 3, 4, 5, 6].map((l) => qs.filter((q) => questionLevel(q) === l).length);
      const calc = c.topic === "calc";
      const lesson = !!LESSON_BY_UNIT[uid]?.steps.some((s) => s.concepts.includes(cid));
      const practice = calc || (lv[0] >= 2 && lv[2] + lv[3] + lv[4] >= 1);
      const test = calc || qs.filter((q) => EXAM_TYPES.includes(q.type)).length >= 3;
      if (!lesson || !practice || !test) gaps++;
      out(`| ${u.source.split(";")[0]} | ${u.title} | ${c.label} | ${objectivesForConcept(c).join(" ") || "—"} | ${yes(lesson)} | ${calc ? "generated" : `${qs.length} (${lv.join("/")})`} | ${actsFor(cid)} | ${yes(practice)} | ${yes(test)} |`);
    }
  }
  out();
}

out("## Objectives (Chapters objectives) → coverage");
out();
out("| Objective | Concepts | Taught | Questions |");
out("|---|---|---|---|");
for (const o of OBJECTIVES) {
  const cs = CONCEPTS.filter(o.match);
  const taught = cs.filter((c) => teachingFor(c.id)).length;
  const qn = cs.reduce((a, c) => a + qFor(c.id).length, 0);
  if (!cs.length || taught < cs.length) gaps++;
  out(`| ${o.id} — ${o.text} | ${cs.length} | ${taught}/${cs.length} | ${o.id === "BP-CALC" ? "generated" : qn} |`);
}
out();
out("## Blueprint content areas → bank");
out();
out("| Content area | Blueprint # | Exam sim # | Questions | Application % |");
out("|---|---|---|---|---|");
for (const t of TOPICS) {
  const qs = QUESTIONS.filter((q) => q.topic === t.id);
  const app = qs.filter((q) => ["apply", "analyze", "evaluate"].includes(q.cognitive)).length;
  out(`| ${t.title} | ${t.min}–${t.max} | ${t.examCount} | ${t.id === "calc" ? "generated" : qs.length} | ${qs.length ? Math.round((app / qs.length) * 100) : "—"} |`);
}
out();
out(`Totals: ${QUESTIONS.length} questions · ${CONCEPTS.length} concepts · ${LESSONS.length} lessons · ${LESSONS.reduce((a, l) => a + l.steps.length, 0)} lesson screens · ${STATIC_ACTIVITIES.length} static activities + ${TEMPLATES.length} generated templates.`);
out();
out(`Gaps flagged: ${gaps}`);
writeFileSync("docs/COVERAGE.md", lines.join("\n") + "\n");
console.log(`docs/COVERAGE.md written — ${gaps} gap(s)`);
